target("game")
    set_kind("binary")
    add_includedirs("$(projectdir)/deps/headeronly", "$(projectdir)/deps/src", "$(projectdir)/src")
    add_includedirs("$(projectdir)/deps/src/glad/include")
    add_includedirs("$(projectdir)/deps/src/imgui-1.83")
    add_files("*.cpp")
    add_packages("spdlog", "glfw")
    add_deps("engine", "glad", "imgui")
    -- add_links("user32", "gdi32", "shell32")