add_requires("spdlog 1.8.5")

target("engine")
    set_kind("shared")
    add_defines("SAMUI_BUILD_DLL")
    add_includedirs("$(projectdir)/deps/headeronly", "$(projectdir)/deps/libs", "$(projectdir)/deps/src")
    add_linkdirs("$(projectdir)/deps/libs/lib_example")
    add_files("*.cpp")
    add_packages("spdlog")
    add_deps("src_example")
    add_links("lib_example")
